function t396_init(recid){var data='';var resolution=t396_detectResolution();var allRecords=document.getElementById('allrecords');var record=document.getElementById('rec'+recid);var zeroBlock=record?record.querySelector('.t396'):null;var artBoard=record?record.querySelector('.t396__artboard'):null;window.tn_window_width=document.documentElement.clientWidth;window.tn_scale_factor=Math.round((window.tn_window_width/resolution)*100)/100;t396_initTNobj();t396_switchResolution(resolution);t396_updateTNobj();t396_artboard_build(data,recid);var isTouchDevice='ontouchend' in document;window.addEventListener('resize',function(){tn_console('>>>> t396: Window on Resize event >>>>');t396_waitForFinalEvent(function(){if(window.isMobile||isTouchDevice){if(document.documentElement.clientWidth!==window.tn_window_width){t396_doResize(recid)}}else{t396_doResize(recid)}},500,'resizeruniqueid'+recid)});window.addEventListener('orientationchange',function(){tn_console('>>>> t396: Orient change event >>>>');t396_waitForFinalEvent(function(){t396_doResize(recid)},600,'orientationuniqueid'+recid)});window.addEventListener('load',function(){t396_allelems__renderView(artBoard);var blockOverflow=artBoard?window.getComputedStyle(artBoard).getPropertyValue('overflow'):'';if(typeof t_lazyload_update==='function'&&blockOverflow==='auto'&&artBoard){artBoard.addEventListener('scroll',t_throttle(function(){var dataLazy=allRecords?allRecords.getAttribute('data-tilda-lazy'):null;if(window.lazy==='y'||dataLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},500))}
if(window.location.hash!==''&&blockOverflow==='visible'){if(artBoard)artBoard.style.overflow='hidden';setTimeout(function(){if(artBoard)artBoard.style.overflow='visible'},1)}});if(document.querySelector('.t830')){window.addEventListener('load',function(){if(allRecords.classList.contains('t830__allrecords_padd')||allRecords.classList.contains('t830__allrecords_padd-small')){t396_doResize(recid)}})}
if(record&&zeroBlock&&artBoard&&record.getAttribute('data-connect-with-tab')==='yes'){zeroBlock.addEventListener('displayChanged',function(){t396_allelems__renderView(artBoard);t396_doResize(recid)});$(zeroBlock).bind('displayChanged',function(){t396_allelems__renderView(artBoard);t396_doResize(recid)})}
setTimeout(function(){if(record&&record.closest('#allrecordstable')&&zeroBlock&&artBoard){zeroBlock.addEventListener('displayChanged',function(){t396_allelems__renderView(artBoard);t396_doResize(recid)});$(zeroBlock).bind('displayChanged',function(){t396_allelems__renderView(artBoard);t396_doResize(recid)})}},1000);if(window.isSafari&&zeroBlock){zeroBlock.classList.add('t396_safari')}
var isScaled=t396_ab__getFieldValue(artBoard,'upscale')==='window';var isTildaModeEdit=allRecords?allRecords.getAttribute('data-tilda-mode')==='edit':null;if(isScaled&&!isTildaModeEdit)t396_scaleBlock(recid)}
function t396_isOnlyScalableBrowser(){var isFirefox=navigator.userAgent.search('Firefox')!==-1;var isOpera=(!!window.opr&&!!window.opr.addons)||!!window.opera||navigator.userAgent.indexOf(' OPR/')!==-1;return isFirefox||isOpera}
function t396_scaleBlock(recid){var isOnlyScalable=t396_isOnlyScalableBrowser();var resolution=t396_detectResolution();var record=document.getElementById('rec'+recid);var elements=record?record.querySelectorAll('.t396__elem'):[];var artBoard=record?record.querySelector('.t396__artboard'):null;if(artBoard){var artBoardWidth=artBoard.clientWidth;var updatedBlockHeight=Math.floor(artBoard.clientHeight*window.tn_scale_factor);var artBoardHeightVH=t396_ab__getFieldValue(artBoard,'height_vh');window.tn_scale_offset=(artBoardWidth*window.tn_scale_factor-artBoardWidth)/2;if(artBoardHeightVH){var artBoardMinHeight=t396_ab__getFieldValue(artBoard,'height');var artBoardMaxHeight=t396_ab__getHeight(artBoard);var scaledMinHeight=artBoardMinHeight*window.tn_scale_factor;updatedBlockHeight=(scaledMinHeight>=artBoardMaxHeight)?scaledMinHeight:artBoardMaxHeight}
artBoard.classList.add('t396__artboard_scale');var styleStr='<style class="t396__scale-style">'+'.t-rec#rec'+recid+' { overflow: visible; }'+'#rec'+recid+' .t396__carrier,'+'#rec'+recid+' .t396__filter,'+'#rec'+recid+' .t396__artboard {'+'height: '+updatedBlockHeight+'px !important;'+'width: 100vw !important;'+'max-width: 100%;'+'}'+'</style>';artBoard.insertAdjacentHTML('beforeend',styleStr)}
Array.prototype.forEach.call(elements,function(elem){var atom=elem.querySelector('.tn-atom');var containerProp=t396_elem__getFieldValue(elem,'container');if(containerProp==='grid'){if(isOnlyScalable){if(atom){var atomParent=atom.parentNode;var div=document.createElement('div');div.classList.add('tn-atom__scale-wrapper');div.style.transform='scale('+window.tn_scale_factor+')';if(atomParent)atomParent.removeChild(atom);div.appendChild(atom);if(atomParent)atomParent.appendChild(div)}}else{elem.style.zoom=window.tn_scale_factor;if(elem.getAttribute('data-elem-type')==='shape'){var elemHeight=t396_elem__getFieldValue(elem,'height');var elemWidth=t396_elem__getFieldValue(elem,'width');var elemStyles=window.getComputedStyle(atom);var elemColor=elemStyles.backgroundColor;var elemBorder=elemStyles.borderWidth;if((elemHeight<=2||elemWidth<=2)&&elemBorder==='0px'){elem.innerHTML='<svg class="tn-atom" xmlns="http://www.w3.org/2000/svg" width="'+elemWidth+'" height="'+elemHeight+'" viewBox="0 0 '+elemWidth+' '+elemHeight+'" fill="none">'+'<rect width="'+elemWidth+'" height="'+elemHeight+'" fill="'+elemColor+'"/>'+'</svg>';var svg=elem.querySelector('svg');var svgStyles=window.getComputedStyle(svg);svg.style.backgroundColor='unset';svg.style.display='block';if(elemHeight<=2){var svgHeight=parseInt(svgStyles.height,10);svg.style.marginLeft='-'+Math.floor(svgHeight/2)+'px';svg.style.marginTop='-'+svgHeight/2+'px'}
if(elemWidth<=2){var svgWidth=parseInt(svgStyles.width,10);svg.style.marginLeft='-'+svgWidth/2+'px';svg.style.marginTop='-'+Math.floor(svgWidth/2)+'px'}}}
if(elem.getAttribute('data-elem-type')==='text'&&resolution<1200&&atom){atom.style.webkitTextSizeAdjust='auto'}
if(atom)atom.style.transformOrigin='center'}}})}
function t396_doResize(recid){var isOnlyScalable=t396_isOnlyScalableBrowser();var record=document.getElementById('rec'+recid);var allRecords=document.getElementById('allrecords');var resolution=t396_detectResolution();var scaleStyle=record?record.querySelector('.t396__scale-style'):null;t396_removeElementFromDOM(scaleStyle);if(!isOnlyScalable){var elements=record?record.querySelectorAll('.t396__elem'):[];Array.prototype.forEach.call(elements,function(element){element.style.zoom='';var atom=element.querySelector('.tn-atom');if(atom)atom.style.transformOrigin=''})}else{var atoms=record?record.querySelectorAll('.tn-atom'):[];Array.prototype.forEach.call(atoms,function(atom){var atomWrapper=atom.closest('.tn-atom__scale-wrapper');var atomParent=atomWrapper?atomWrapper.parentNode:null;if(atomParent)atomParent.removeChild(atomWrapper);if(atomParent)atomParent.appendChild(atom)})}
var artBoard=record?record.querySelector('.t396__artboard'):null;var artBoardWidth=artBoard?artBoard.clientWidth:0;window.tn_window_width=window.isMobile?document.documentElement.clientWidth:window.innerWidth;window.tn_scale_factor=Math.round((window.tn_window_width/resolution)*100)/100;window.tn_scale_offset=(artBoardWidth*window.tn_scale_factor-artBoardWidth)/2;t396_switchResolution(resolution);t396_updateTNobj();t396_ab__renderView(artBoard);t396_allelems__renderView(artBoard);var tildaMode=allRecords?allRecords.getAttribute('data-tilda-mode'):'';var isScaled=t396_ab__getFieldValue(artBoard,'upscale')==='window';if(isScaled&&tildaMode!=='edit')t396_scaleBlock(recid)}
function t396_detectResolution(){var windowWidth=window.isMobile?document.documentElement.clientWidth:window.innerWidth;var resolution=1200;var breakpoints=[1200,960,640,480,320];for(var i=0;i<breakpoints.length-1;i++){if(windowWidth<breakpoints[i]){resolution=breakpoints[i+1]}}
return resolution}
function t396_initTNobj(){tn_console('func: initTNobj');window.tn={};window.tn.canvas_min_sizes=['320','480','640','960','1200'];window.tn.canvas_max_sizes=['480','640','960','1200',''];window.tn.ab_fields=['height','width','bgcolor','bgimg','bgattachment','bgposition','filteropacity','filtercolor','filteropacity2','filtercolor2','height_vh','valign']}
function t396_updateTNobj(){tn_console('func: updateTNobj');var allRecords=document.getElementById('allrecords');var allRecPaddingLeft=allRecords?window.getComputedStyle(allRecords).paddingLeft||'0':'0';allRecPaddingLeft=parseInt(allRecPaddingLeft,10);var allRecPaddingRight=allRecords?window.getComputedStyle(allRecords).paddingRight||'0':'0';allRecPaddingRight=parseInt(allRecPaddingRight,10);if(window.zero_window_width_hook&&window.zero_window_width_hook==='allrecords'&&allRecords){window.tn.window_width=allRecords.clientWidth-(allRecPaddingLeft+allRecPaddingRight)}else{window.tn.window_width=document.documentElement.clientWidth}
window.tn.window_height=document.documentElement.clientHeight;window.tn.curResolution;var breakpoints=[1200,960,640,480,320];for(var i=0;i<breakpoints.length;i++){if(+window.tn.curResolution===breakpoints[i]){window.tn.canvas_min_width=breakpoints[i];window.tn.canvas_max_width=i===0?window.tn.window_width:breakpoints[i-1]}}
window.tn.grid_width=window.tn.canvas_min_width;window.tn.grid_offset_left=(window.tn.window_width-window.tn.grid_width)/2}
var t396_waitForFinalEvent=(function(){var timers={};return function(callback,ms,uniqueId){if(!uniqueId){uniqueId='Don\'t call this twice without a uniqueId'}
if(timers[uniqueId]){clearTimeout(timers[uniqueId])}
timers[uniqueId]=setTimeout(callback,ms)}})();function t396_switchResolution(resolution,resolutionMax){tn_console('func: switchResolution');if(typeof resolutionMax==='undefined'){var breakpoints=[1200,960,640,480,320];breakpoints.forEach(function(breakpoint,i){if(+resolution===breakpoint){resolutionMax=i===0?'':breakpoints[i-1]}})}
window.tn.curResolution=resolution;window.tn.curResolution_max=resolutionMax}
function t396_artboard_build(data,recid){tn_console('func: t396_artboard_build. Recid:'+recid);tn_console(data);var record=document.getElementById('rec'+recid);var allRecords=document.getElementById('allrecords');var artBoard=record?record.querySelector('.t396__artboard'):null;if(!artBoard)return!1;t396_ab__renderView(artBoard);var elements=artBoard.querySelectorAll('.tn-elem');Array.prototype.forEach.call(elements,function(element){var dataType=element.getAttribute('data-elem-type');switch(dataType){case 'text':t396_addText(artBoard,element);break;case 'image':t396_addImage(artBoard,element);break;case 'shape':t396_addShape(artBoard,element);break;case 'button':t396_addButton(artBoard,element);break;case 'video':t396_addVideo(artBoard,element);break;case 'html':t396_addHtml(artBoard,element);break;case 'tooltip':t396_addTooltip(artBoard,element);break;case 'form':t396_addForm(artBoard,element);break;case 'gallery':t396_addGallery(artBoard,element);break}});artBoard.classList.remove('rendering');artBoard.classList.add('rendered');var artBoardOverflow=artBoard.getAttribute('data-artboard-ovrflw');if((artBoardOverflow==='visible'||artBoardOverflow==='visibleX')&&allRecords){allRecords.style.overflow='hidden'}
if(artBoardOverflow==='auto'){var diff=Math.abs(artBoard.offsetHeight-artBoard.clientHeight);if(diff!==0){artBoard.style.paddingBottom=diff+'px'}}
if(window.isMobile){var style=document.createElement('style');style.textContent='@media only screen and (min-width:1366px) and (orientation:landscape) and (-webkit-min-device-pixel-ratio:2) {.t396__carrier {background-attachment:scroll!important;}}';record.insertAdjacentElement('beforeend',style)}}
function t396_ab__renderView(artBoard){if(!artBoard)return!1;var fields=window.tn.ab_fields;var allRecords=document.getElementById('allrecords');var artBoardHeightVH;for(var i=0;i<fields.length;i++){t396_ab__renderViewOneField(artBoard,fields[i])}
var artBoardMinHeight=t396_ab__getFieldValue(artBoard,'height');var artBoardMaxHeight=t396_ab__getHeight(artBoard);var isTildaModeEdit=allRecords?allRecords.getAttribute('data-tilda-mode')==='edit':!1;var isScaled=t396_ab__getFieldValue(artBoard,'upscale')==='window';artBoardHeightVH=t396_ab__getFieldValue(artBoard,'height_vh');if(isScaled&&!isTildaModeEdit&&artBoardHeightVH){var scaledMinHeight=parseInt(artBoardMinHeight,10)*window.tn_scale_factor}
var offsetTop;if(artBoardMinHeight===artBoardMaxHeight||(scaledMinHeight&&scaledMinHeight>=artBoardMaxHeight)){offsetTop=0}else{var artBoardVerticalAlign=t396_ab__getFieldValue(artBoard,'valign');switch(artBoardVerticalAlign){case 'top':offsetTop=0;break;case 'center':if(scaledMinHeight){offsetTop=parseFloat(((artBoardMaxHeight-scaledMinHeight)/2).toFixed(1))}else{offsetTop=parseFloat(((artBoardMaxHeight-artBoardMinHeight)/2).toFixed(1))}
break;case 'bottom':if(scaledMinHeight){offsetTop=parseFloat((artBoardMaxHeight-scaledMinHeight).toFixed(1))}else{offsetTop=parseFloat((artBoardMaxHeight-artBoardMinHeight).toFixed(1))}
break;case 'stretch':offsetTop=0;artBoardMinHeight=artBoardMaxHeight;break;default:offsetTop=0;break}}
artBoard.setAttribute('data-artboard-proxy-min-offset-top',offsetTop);artBoard.setAttribute('data-artboard-proxy-min-height',artBoardMinHeight);artBoard.setAttribute('data-artboard-proxy-max-height',artBoardMaxHeight);var filter=artBoard.querySelector('.t396__filter');var carrier=artBoard.querySelector('.t396__carrier');artBoardHeightVH=t396_ab__getFieldValue(artBoard,'height_vh');artBoardHeightVH=parseFloat(artBoardHeightVH);if(window.isMobile&&artBoardHeightVH){var height=document.documentElement.clientHeight*artBoardHeightVH/100;artBoard.style.height=height+'px';if(filter)filter.style.height=height+'px';if(carrier)carrier.style.height=height+'px'}}
function t396_addText(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addText');var fieldsString='top,left,width,container,axisx,axisy,widthunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_addImage(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addImage');var fieldsString='img,width,filewidth,fileheight,top,left,container,axisx,axisy,widthunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element);var images=element.querySelectorAll('img');Array.prototype.forEach.call(images,function(img){img.addEventListener('load',function(){t396_elem__renderViewOneField(element,'top');if(img.src){setTimeout(function(){t396_elem__renderViewOneField(element,'top')},2000)}});if(img.complete){t396_elem__renderViewOneField(element,'top');if(img.src){setTimeout(function(){t396_elem__renderViewOneField(element,'top')},2000)}}
img.addEventListener('tuwidget_done',function(){t396_elem__renderViewOneField(element,'top')})})}
function t396_addShape(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addShape');var fieldsString='width,height,top,left,';fieldsString+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_addButton(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addButton');var fieldsString='top,left,width,height,container,axisx,axisy,caption,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element);return(element)}
function t396_addVideo(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addVideo');var fieldsString='width,height,top,left,';fieldsString+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element);var videoEl=element.querySelector('.tn-atom__videoiframe');var atom=element.querySelector('.tn-atom');if(atom)atom.style.backgroundColor='#000';var videoCover=atom?atom.getAttribute('data-atom-video-has-cover'):'';if(!videoCover)videoCover='';if(videoCover==='y'&&atom){atom.addEventListener('click',function(){var iframe=videoEl?videoEl.querySelector('iframe'):null;var dataOriginal=iframe?iframe.getAttribute('data-original'):'';if(iframe)iframe.setAttribute('src',dataOriginal);atom.style.backgroundImage='none';var playBtn=atom.querySelector('.tn-atom__video-play-link');if(playBtn)playBtn.style.display='none'})}
var allRecords=document.getElementById('allrecords');var autoplay=t396_elem__getFieldValue(element,'autoplay');var showinfo=t396_elem__getFieldValue(element,'showinfo');var loop=t396_elem__getFieldValue(element,'loop');var mute=t396_elem__getFieldValue(element,'mute');var startSec=t396_elem__getFieldValue(element,'startsec');var endSec=t396_elem__getFieldValue(element,'endsec');var tildaMode=allRecords?allRecords.getAttribute('data-tilda-mode'):'';var url='';var script=document.createElement('script');script.textContent='lazyload_iframe = new LazyLoad({elements_selector: ".t-iframe"});';var youtubeID=videoEl?videoEl.getAttribute('data-youtubeid'):'';if(youtubeID){url='//youtube.com/embed/';url+=youtubeID+'?rel=0&fmt=18&html5=1';url+='&showinfo='+(showinfo==='y'?'1':'0');if(loop==='y'){url+='&loop=1&playlist='+youtubeID}
if(startSec>0){url+='&start='+startSec}
if(endSec>0){url+='&end='+endSec}
if(mute==='y'){url+='&mute=1'}
if(videoCover==='y'){url+='&autoplay=1';var instFlag='y';var iframeClass='';if(autoplay==='y'&&mute==='y'&&window.lazy==='y'){instFlag='lazy';iframeClass=' class="t-iframe"'}
videoEl.innerHTML='<iframe id="youtubeiframe"'+iframeClass+' width="100%" height="100%" data-original="'+url+'" frameborder="0" allowfullscreen data-flag-inst="'+instFlag+'"></iframe>';if(autoplay==='y'&&mute==='y'&&window.lazy==='y'){element.insertAdjacentElement('beforeend',script)}
if(autoplay==='y'&&mute==='y'){atom.click()}}else{if(tildaMode!=='edit'&&autoplay==='y'){url+='&autoplay=1'}
if(window.lazy==='y'){videoEl.innerHTML='<iframe id="youtubeiframe" class="t-iframe" width="100%" height="100%" data-original="'+url+'" frameborder="0" allowfullscreen data-flag-inst="lazy"></iframe>';element.insertAdjacentElement('beforeend',script)}else{videoEl.innerHTML='<iframe id="youtubeiframe" width="100%" height="100%" src="'+url+'" frameborder="0" allowfullscreen data-flag-inst="y"></iframe>'}}}
var vimeoID=videoEl?videoEl.getAttribute('data-vimeoid'):'';if(vimeoID){url='//player.vimeo.com/video/';url+=vimeoID+'?color=ffffff&badge=0';if(showinfo==='y'){url+='&title=1&byline=1&portrait=1'}else{url+='&title=0&byline=0&portrait=0'}
if(loop==='y'){url+='&loop=1'}
if(mute==='y'){url+='&muted=1'}
if(videoCover==='y'){url+='&autoplay=1';videoEl.innerHTML='<iframe data-original="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'}else{if(tildaMode!=='edit'&&autoplay==='y'){url+='&autoplay=1'}
if(window.lazy==='y'){videoEl.innerHTML='<iframe class="t-iframe" data-original="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>';element.insertAdjacentElement('beforeend',script)}else{videoEl.innerHTML='<iframe src="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'}}}}
function t396_addHtml(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addHtml');var fieldsString='width,height,top,left,';fieldsString+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_addTooltip(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addTooltip');var fieldsString='width,height,top,left,';fieldsString+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits,tipposition';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element);var tooltip=element.querySelector('.tn-atom__pin');var tooltipContent=element.querySelector('.tn-atom__tip');var tooltipOpenTrigger=element.getAttribute('data-field-tipopen-value');if(window.isMobile||tooltipOpenTrigger==='click'){t396_setUpTooltip_mobile(element,tooltip,tooltipContent)}else{t396_setUpTooltip_desktop(element,tooltip,tooltipContent)}
setTimeout(function(){var atomImages=document.querySelectorAll('.tn-atom__tip-img');Array.prototype.forEach.call(atomImages,function(img){var imgOriginal=img.getAttribute('data-tipimg-original');if(imgOriginal)img.src=imgOriginal})},3000)}
function t396_addForm(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addForm');var fieldsString='width,top,left,';fieldsString+='inputs,container,axisx,axisy,widthunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_addGallery(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addForm');var fieldsString='width,height,top,left,';fieldsString+='imgs,container,axisx,axisy,widthunits,heightunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_elem__setFieldValue(element,prop,val,flag_render,flag_updateui,resolution){element=t396_getEl(element);if(!element)return;if(!resolution)resolution=window.tn.curResolution;if(+resolution<1200&&prop!=='zindex'){element.setAttribute('data-field-'+prop+'-res-'+resolution+'-value',val)}else{element.setAttribute('data-field-'+prop+'-value',val)}
if(flag_render==='render')elem__renderViewOneField(element,prop);if(flag_updateui==='updateui')panelSettings__updateUi(element,prop,val)}
function t396_elem__getFieldValue(element,prop){element=t396_getEl(element);if(!element)return;var resolution=window.tn.curResolution;var breakpoints=[1200,960,640,480,320];var dataField;breakpoints.forEach(function(breakpoint,i){if(i===0&&+resolution>=breakpoint){dataField=element.getAttribute('data-field-'+prop+'-value')}
if(i>0&&+resolution===breakpoint){dataField=element.getAttribute('data-field-'+prop+'-res-'+breakpoint+'-value');if(i>1&&!dataField){var slicedBreakpoints=breakpoints.slice(1,i);for(var n=slicedBreakpoints.length-1;n>=0;n--){dataField=element.getAttribute('data-field-'+prop+'-res-'+slicedBreakpoints[n]+'-value');if(dataField)break}}
if(!dataField)dataField=element.getAttribute('data-field-'+prop+'-value')}});return dataField?dataField:''}
function t396_elem__renderView(element){element=t396_getEl(element);tn_console('func: elem__renderView');var fields=element?element.getAttribute('data-fields'):'';if(!fields)return!1;fields=fields.split(',');fields.forEach(function(field){t396_elem__renderViewOneField(element,field)})}
function t396_elem__renderViewOneField(element,field){element=t396_getEl(element);if(!element)return;var value=t396_elem__getFieldValue(element,field);var elementType;var borderWidth;var borderStyle;var currentValue;var slidesMain;var slidesImg;switch(field){case 'left':value=t396_elem__convertPosition__Local__toAbsolute(element,field,value);element.style.left=parseFloat(value).toFixed(1)+'px';break;case 'top':value=t396_elem__convertPosition__Local__toAbsolute(element,field,value);element.style.top=parseFloat(value).toFixed(1)+'px';break;case 'width':value=t396_elem__getWidth(element,value);element.style.width=parseFloat(value).toFixed(1)+'px';elementType=element.getAttribute('data-elem-type');switch(elementType){case 'tooltip':var pinSvgIcon=element.querySelectorAll('.tn-atom__pin-icon');Array.prototype.forEach.call(pinSvgIcon,function(pin){var pinSize=parseFloat(value).toFixed(1)+'px';pin.style.width=pinSize;pin.style.height=pinSize});element.style.height=parseInt(value).toFixed(1)+'px';break;case 'gallery':borderWidth=t396_elem__getFieldValue(element,'borderwidth');borderStyle=t396_elem__getFieldValue(element,'borderstyle');if(!borderStyle||!borderWidth||borderStyle==='none'){borderWidth=0}
value-=borderWidth*2;currentValue=parseFloat(value).toFixed(1)+'px';slidesMain=element.querySelector('.t-slds__main');slidesImg=element.querySelectorAll('.tn-atom__slds-img');element.style.width=currentValue;if(slidesMain)slidesMain.style.width=currentValue;Array.prototype.forEach.call(slidesImg,function(img){img.style.width=currentValue});break}
break;case 'height':elementType=element.getAttribute('data-elem-type');if(elementType==='tooltip')return;value=t396_elem__getHeight(element,value);element.style.height=parseFloat(value).toFixed(1)+'px';if(elementType==='gallery'){borderWidth=t396_elem__getFieldValue(element,'borderwidth');borderStyle=t396_elem__getFieldValue(element,'borderstyle');if(!borderStyle||!borderWidth||borderStyle==='none'){borderWidth=0}
value-=borderWidth*2;currentValue=parseFloat(value).toFixed(1)+'px';slidesMain=element.querySelector('.t-slds__main');slidesImg=element.querySelectorAll('.tn-atom__slds-img');element.style.height=currentValue;if(slidesMain)slidesMain.style.height=currentValue;Array.prototype.forEach.call(slidesImg,function(img){img.style.height=currentValue})}
break;case 'container':t396_elem__renderViewOneField(element,'left');t396_elem__renderViewOneField(element,'top');break;case 'inputs':var textArea=element.querySelector('.tn-atom__inputs-textarea');value=textArea?textArea.value:'';try{t_zeroForms__renderForm($(element),value)}catch(err){}
break}
if(field==='width'||field==='height'||field==='fontsize'||field==='fontfamily'||field==='letterspacing'||field==='fontweight'||field==='img'){t396_elem__renderViewOneField(element,'left');t396_elem__renderViewOneField(element,'top')}}
function t396_elem__convertPosition__Local__toAbsolute(element,field,value){element=t396_getEl(element);if(!element)return;var artBoard=element.closest('.t396__artboard');var verticalAlignValue=t396_ab__getFieldValue(artBoard,'valign');var isScaled=t396_ab__getFieldValue(artBoard,'upscale')==='window';var allRecords=document.getElementById('allrecords');var tildaMode=allRecords?allRecords.getAttribute('data-tilda-mode'):'';var isTildaModeEdit=tildaMode==='edit';var isOnlyScalable=t396_isOnlyScalableBrowser();var isScaledElement=!isTildaModeEdit&&isScaled&&isOnlyScalable;var isZoomedElement=!isTildaModeEdit&&isScaled&&!isOnlyScalable;var valueAxisY=t396_elem__getFieldValue(element,'axisy');var valueAxisX=t396_elem__getFieldValue(element,'axisx');var container=t396_elem__getFieldValue(element,'container');value=parseInt(value);var elementContainer;var offsetLeft;var offsetTop;var elementWidth;var elementContainerWidth;var elementHeight;var elementContainerHeight;switch(field){case 'left':elementContainer=container==='grid'?'grid':'window';offsetLeft=container==='grid'?window.tn.grid_offset_left:0;elementContainerWidth=container==='grid'?window.tn.grid_width:window.tn.window_width;var elementLeftUnits=t396_elem__getFieldValue(element,'leftunits');if(elementLeftUnits==='%'){value=t396_roundFloat(elementContainerWidth*value/100)}
if(!isTildaModeEdit&&isScaled){if(container==='grid'&&isOnlyScalable)value=value*window.tn_scale_factor}else{value=offsetLeft+value}
if(valueAxisX==='center'){elementWidth=t396_elem__getWidth(element);if(isScaledElement&&elementContainer!=='window'){elementContainerWidth*=window.tn_scale_factor;elementWidth*=window.tn_scale_factor}
value=elementContainerWidth/2-elementWidth/2+value}
if(valueAxisX==='right'){elementWidth=t396_elem__getWidth(element);if(isScaledElement&&elementContainer!=='window'){elementContainerWidth*=window.tn_scale_factor;elementWidth*=window.tn_scale_factor}
value=elementContainerWidth-elementWidth+value}
if(isScaledElement&&elementContainer!=='window'){elementWidth=t396_elem__getWidth(element);value=value+(elementWidth*window.tn_scale_factor-elementWidth)/2}
break;case 'top':var artBoardParent=element.parentNode;var proxyMinOffsetTop=artBoardParent?artBoardParent.getAttribute('data-artboard-proxy-min-offset-top'):'0';var proxyMinHeight=artBoardParent?artBoardParent.getAttribute('data-artboard-proxy-min-height'):'0';var proxyMaxHeight=artBoardParent?artBoardParent.getAttribute('data-artboard-proxy-max-height'):'0';var getElementHeight=function(element){var height=t396_elem__getHeight(element);if(element&&element.getAttribute('data-elem-type')==='image'){var width=t396_elem__getWidth(element);var fileWidth=t396_elem__getFieldValue(element,'filewidth');var fileHeight=t396_elem__getFieldValue(element,'fileheight');if(fileWidth&&fileHeight){var ratio=parseInt(fileWidth)/parseInt(fileHeight);height=width/ratio}}
return height};elementContainer=container==='grid'?'grid':'window';offsetTop=container==='grid'?parseFloat(proxyMinOffsetTop):0;elementContainerHeight=container==='grid'?parseFloat(proxyMinHeight):parseFloat(proxyMaxHeight);var elTopUnits=t396_elem__getFieldValue(element,'topunits');if(elTopUnits==='%'){value=(elementContainerHeight*(value/100))}
if(isScaledElement&&elementContainer!=='window'){value*=window.tn_scale_factor}
if(isZoomedElement&&elementContainer!=='window'){offsetTop=verticalAlignValue==='stretch'?0:(offsetTop/window.tn_scale_factor)}
value=offsetTop+value;var artBoardHeightVH=t396_ab__getFieldValue(artBoardParent,'height_vh');var artBoardMinHeight=t396_ab__getFieldValue(artBoardParent,'height');var artBoardMaxHeight=t396_ab__getHeight(artBoardParent);if(isScaled&&!isTildaModeEdit&&artBoardHeightVH){var scaledMinHeight=parseInt(artBoardMinHeight,10)*window.tn_scale_factor}
if(valueAxisY==='center'){elementHeight=getElementHeight(element);if(isScaledElement&&elementContainer!=='window'){if(verticalAlignValue!=='stretch'){elementContainerHeight=elementContainerHeight*window.tn_scale_factor}else{if(scaledMinHeight){elementContainerHeight=scaledMinHeight>artBoardMaxHeight?scaledMinHeight:artBoardMaxHeight}else{elementContainerHeight=artBoardParent.clientHeight}}
elementHeight*=window.tn_scale_factor}
if(!isTildaModeEdit&&isScaled&&!isOnlyScalable&&elementContainer!=='window'&&verticalAlignValue==='stretch'){if(scaledMinHeight){elementContainerHeight=scaledMinHeight>artBoardMaxHeight?scaledMinHeight:artBoardMaxHeight}else{elementContainerHeight=artBoardParent.clientHeight}
elementContainerHeight=elementContainerHeight/window.tn_scale_factor}
value=elementContainerHeight/2-elementHeight/2+value}
if(valueAxisY==='bottom'){elementHeight=getElementHeight(element);if(isScaledElement&&elementContainer!=='window'){if(verticalAlignValue!=='stretch'){elementContainerHeight=elementContainerHeight*window.tn_scale_factor}else{if(scaledMinHeight){elementContainerHeight=scaledMinHeight>artBoardMaxHeight?scaledMinHeight:artBoardMaxHeight}else{elementContainerHeight=artBoardParent.clientHeight}}
elementHeight*=window.tn_scale_factor}
if(!isTildaModeEdit&&isScaled&&!isOnlyScalable&&elementContainer!=='window'&&verticalAlignValue==='stretch'){if(scaledMinHeight){elementContainerHeight=scaledMinHeight>artBoardMaxHeight?scaledMinHeight:artBoardMaxHeight}else{elementContainerHeight=artBoardParent.clientHeight}
elementContainerHeight=elementContainerHeight/window.tn_scale_factor}
value=elementContainerHeight-elementHeight+value}
if(isScaledElement&&elementContainer!=='window'){elementHeight=getElementHeight(element);value=value+(elementHeight*window.tn_scale_factor-elementHeight)/2}
break}
return value}
function t396_ab__setFieldValue(artBoard,prop,val,resolution){if(!resolution)resolution=window.tn.curResolution;if(resolution<1200){if(artBoard)artBoard.setAttribute('data-artboard-'+prop+'-res-'+resolution,val)}else{if(artBoard)artBoard.setAttribute('data-artboard-'+prop,val)}}
function t396_ab__getFieldValue(artBoard,prop){if(!artBoard)return;var resolution=window.tn.curResolution;var breakpoints=[1200,960,640,480,320];var dataField;breakpoints.forEach(function(breakpoint,i){if(i===0&&+resolution>=breakpoint){dataField=artBoard.getAttribute('data-artboard-'+prop)}
if(i>0&&+resolution===breakpoint){dataField=artBoard.getAttribute('data-artboard-'+prop+'-res-'+breakpoint);if(i>1&&!dataField){var slicedBreakpoints=breakpoints.slice(1,i);for(var n=slicedBreakpoints.length-1;n>=0;n--){dataField=artBoard.getAttribute('data-artboard-'+prop+'-res-'+slicedBreakpoints[n]);if(dataField)break}}
if(!dataField)dataField=artBoard.getAttribute('data-artboard-'+prop)}});return dataField?dataField:''}
function t396_ab__renderViewOneField(artBoard,field){t396_ab__getFieldValue(artBoard,field)}
function t396_allelems__renderView(artBoard){if(!artBoard)return!1;tn_console('func: allelems__renderView: abid:'+artBoard.getAttribute('data-artboard-recid'));var ArtBoardelements=artBoard.querySelectorAll('.tn-elem');Array.prototype.forEach.call(ArtBoardelements,function(element){t396_elem__renderView(element)})}
function t396_ab__filterUpdate(artBoard){var filter=artBoard.querySelector('.t396__filter');if(!filter)return;var filterColorRgb=filter.getAttribute('data-filtercolor-rgb');var filterColorRgb2=filter.getAttribute('data-filtercolor2-rgb');var filterOpacity=filter.getAttribute('data-filteropacity');var filterOpacity2=filter.getAttribute('data-filteropacity2');if(filterColorRgb&&!filterColorRgb2){filter.style.backgroundColor='rgba('+filterColorRgb+','+filterOpacity+')'}else if(!filterColorRgb&&filterColorRgb2){filter.style.backgroundColor='rgba('+filterColorRgb2+','+filterOpacity2+')'}else if(filterColorRgb&&filterColorRgb2){filter.style.background='-webkit-gradient(linear, left top, left bottom, from(rgba('+filterColorRgb+','+filterOpacity+')), to(rgba('+filterColorRgb2+','+filterOpacity2+')) )'}else{filter.style.backgroundColor='transparent'}}
function t396_ab__getHeight(artBoard,artBoardHeight){if(!artBoardHeight)artBoardHeight=t396_ab__getFieldValue(artBoard,'height');artBoardHeight=parseFloat(artBoardHeight);var artBoardHeightVH=t396_ab__getFieldValue(artBoard,'height_vh');if(artBoardHeightVH){artBoardHeightVH=parseFloat(artBoardHeightVH);if(!isNaN(artBoardHeightVH)){var artBoardHeightVHpx=window.tn.window_height*artBoardHeightVH/100;if(artBoardHeight<artBoardHeightVHpx){artBoardHeight=artBoardHeightVHpx}}}
return artBoardHeight}
function t396_hex2rgb(hexStr){var hex=parseInt(hexStr.substring(1),16);var r=(hex&0xff0000)>>16;var g=(hex&0x00ff00)>>8;var b=hex&0x0000ff;return[r,g,b]}
String.prototype.t396_replaceAll=function(search,replacement){var target=this;return target.replace(new RegExp(search,'g'),replacement)};function t396_elem__getWidth(element,value){element=t396_getEl(element);if(!value)value=t396_elem__getFieldValue(element,'width');value=parseFloat(value);var elWidthUnits=t396_elem__getFieldValue(element,'widthunits');if(elWidthUnits==='%'){var elementContainer=t396_elem__getFieldValue(element,'container');if(elementContainer==='window'){value=window.tn.window_width*value/100}else{value=window.tn.grid_width*value/100}}
return value}
function t396_elem__getHeight(element,value){element=t396_getEl(element);if(!value)value=t396_elem__getFieldValue(element,'height');value=parseFloat(value);var elemType=element.getAttribute('data-elem-type');if(elemType==='shape'||elemType==='video'||elemType==='html'||elemType==='gallery'){var elHeightUnits=t396_elem__getFieldValue(element,'heightunits');if(elHeightUnits==='%'){var artBoard=element.parentNode;var proxyMinHeight=artBoard?artBoard.getAttribute('data-artboard-proxy-min-height'):'0';var proxyMaxHeight=artBoard?artBoard.getAttribute('data-artboard-proxy-max-height'):'0';var artBoardMinHeight=parseFloat(proxyMinHeight);var artBoardMaxHeight=parseFloat(proxyMaxHeight);var elementContainer=t396_elem__getFieldValue(element,'container');if(elementContainer==='window'){value=artBoardMaxHeight*(value/100)}else{value=artBoardMinHeight*(value/100)}}}else if(elemType!=='button'){value=element.clientHeight}
return value}
function t396_roundFloat(n){n=Math.round(n*100)/100;return(n)}
function tn_console(str){if(+(window.tn_comments)===1)console.log(str)}
function t396_setUpTooltip_desktop(element,tooltip,tooltipContent){element=t396_getEl(element);var timer;if(tooltip){tooltip.addEventListener('mouseover',function(){var visibleEls=document.querySelectorAll('.tn-atom__tip_visible');Array.prototype.forEach.call(visibleEls,function(visibleEl){var curTipEl=visibleEl.closest('.t396__elem');var cirTipElID=curTipEl?curTipEl.getAttribute('data-elem-id'):'';if(cirTipElID!==element.getAttribute('data-elem-id')){t396_hideTooltip(curTipEl,visibleEl)}});clearTimeout(timer);if(tooltipContent&&tooltipContent.style.display==='block')return;t396_showTooltip(element,tooltipContent)});tooltip.addEventListener('mouseout',function(){timer=setTimeout(function(){t396_hideTooltip(element,tooltipContent)},300)})}}
function t396_setUpTooltip_mobile(element,tooltip,tooltipContent){element=t396_getEl(element);if(tooltip){tooltip.addEventListener('click',function(){if(tooltipContent&&tooltipContent.style.display==='block'&&tooltip.classList.contains('tn-atom__pin')){t396_hideTooltip(element,tooltipContent)}else{t396_showTooltip(element,tooltipContent)}})}
var elementID=element.getAttribute('data-elem-id');document.addEventListener('click',function(e){if(e.target.closest('.tn-atom__pin')){var zbEl=e.target.closest('.t396__elem');var clickedPinId=zbEl?zbEl.getAttribute('data-elem-id'):'';if(clickedPinId===elementID)return}
t396_hideTooltip(element,tooltipContent)})}
function t396_hideTooltip(element,tooltipContent){if(tooltipContent)tooltipContent.style.display='';if(tooltipContent)tooltipContent.style.left='';if(tooltipContent)tooltipContent.style.transform='';if(tooltipContent)tooltipContent.style.right='';if(tooltipContent)tooltipContent.classList.remove('tn-atom__tip_visible');if(element)element.style.zIndex=''}
function t396_showTooltip(element,tooltipContent){element=t396_getEl(element);var pos=element.getAttribute('data-field-tipposition-value');if(!pos)pos='top';var elSize=element.clientHeight;var elTop=element.getBoundingClientRect().top+window.pageYOffset;var elBottom=elTop+elSize;var elLeft=element.getBoundingClientRect().left+window.pageXOffset;var elRight=elLeft+elSize;var winTop=window.pageYOffset;var winWidth=document.documentElement.clientWidth;var winBottom=winTop+document.documentElement.clientHeight;if(tooltipContent)tooltipContent.style.display='block';if(tooltipContent)tooltipContent.style.zIndex='-9999';if(tooltipContent)tooltipContent.style.transform='translateX(-10000px)';var tipElHeight=tooltipContent?tooltipContent.offsetHeight:0;var tipElWidth=tooltipContent?tooltipContent.offsetWidth:0;if(tooltipContent)tooltipContent.style.display='';if(tooltipContent)tooltipContent.style.zIndex='';if(tooltipContent)tooltipContent.style.transform='';var padding=15;var tipElRight;var tipElLeft;var tipElTop;var tipElBottom;if(pos==='right'||pos==='left'){tipElRight=elRight+padding+tipElWidth;tipElLeft=elLeft-padding-tipElWidth;if((pos==='right'&&tipElRight>winWidth)||(pos==='left'&&tipElLeft<0)){pos='top'}}
if(pos==='top'||pos==='bottom'){tipElRight=elRight+(tipElWidth/2-elSize/2);tipElLeft=elLeft-(tipElWidth/2-elSize/2);if(tipElRight>winWidth){var rightOffset=-(winWidth-elRight-padding);if(tooltipContent)tooltipContent.style.left='auto';if(tooltipContent)tooltipContent.style.transform='none';if(tooltipContent)tooltipContent.style.right=rightOffset+'px'}
if(tipElLeft<0){var leftOffset=-(elLeft-padding);if(tooltipContent)tooltipContent.style.left=leftOffset+'px';if(tooltipContent)tooltipContent.style.transform='none'}}
if(pos==='top'){tipElTop=elTop-padding-tipElHeight;tipElBottom=elBottom+padding+tipElHeight;if(winBottom>tipElBottom&&winTop>tipElTop){pos='bottom'}}
if(pos==='bottom'){tipElTop=elTop-padding-tipElHeight;tipElBottom=elBottom+padding+tipElHeight;if(winBottom<tipElBottom&&winTop<tipElTop){pos='top'}}
if(tooltipContent)tooltipContent.setAttribute('data-tip-pos',pos);if(tooltipContent)tooltipContent.style.display='block';if(tooltipContent)tooltipContent.classList.add('tn-atom__tip_visible');if(element)element.style.zIndex='1000'}
function t396_hex2rgba(hexStr,opacity){if(!hexStr)return!1;var hex=parseInt(hexStr.substring(1),16);var r=(hex&0xff0000)>>16;var g=(hex&0x00ff00)>>8;var b=hex&0x0000ff;return[r,g,b,parseFloat(opacity)]}
function t396_removeElementFromDOM(el){el=t396_getEl(el);if(el&&el.parentNode){el.parentNode.removeChild(el)}}
function t396_getEl(el){if(el instanceof jQuery){return el.length?el.get(0):null}else{return el}}
if(!Element.prototype.matches){Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.msMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.webkitMatchesSelector||Element.prototype.oMatchesSelector}
if(!Element.prototype.closest){Element.prototype.closest=function(s){var el=this;while(el&&el.nodeType===1){if(Element.prototype.matches.call(el,s)){return el}
el=el.parentElement||el.parentNode}
return null}}
function t585_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var accordion=rec.querySelectorAll('.t585__accordion')[0];var headers=rec.querySelectorAll('.t585__header');var isLazy=document.getElementById('allrecords').getAttribute('data-tilda-lazy');var accordionScroll;if(accordion){accordionScroll=accordion.getAttribute('data-scroll-to-expanded');accordion=accordion.getAttribute('data-accordion')}else{accordion='false';accordionScroll='false'}
for(var i=0;i<headers.length;i++){headers[i].addEventListener('click',function(){var element=this;var container=element.nextElementSibling;var activeHeight=0;var isAccordionDown=!1;if(element.classList.contains('t585__opened')){element.classList.remove('t585__opened');t585_accordionHide(container)}else{if(accordionScroll==='true'&&accordion==='true'){activeHeight=t585__getOldAction(rec);isAccordionDown=t585__getAccordionPosition(headers,element)}
if(accordion==='true')t585_accordionAllHide(headers);element.classList.add('t585__opened');container.style.display='block';var height=container.scrollHeight;container.style.maxHeight='0px';setTimeout(function(){container.style.maxHeight=height+'px';if(accordionScroll==='true'){t585__calcHeight(element,container,activeHeight,isAccordionDown)}},0)}
if(window.lazy==='y'||isLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}}
function t585_accordionAllHide(headers){for(var i=0;i<headers.length;i++){var elementHide=headers[i];elementHide.classList.remove('t585__opened');t585_accordionHide(elementHide.nextElementSibling)}}
function t585_accordionHide(container){if(!container.style.maxHeight)container.style.maxHeight=container.scrollHeight+'px';setTimeout(function(){container.style.maxHeight='0px'},0)}
function t585__getOldAction(rec){var activeHeader=rec.querySelector('.t585__opened');var activeHeight=0;if(activeHeader)var activeContainer=activeHeader.nextElementSibling;if(activeContainer)activeHeight=activeContainer.offsetHeight;return activeHeight}
function t585__getAccordionPosition(headers,element){var oldIndex;var newIndex;for(var i=0;i<headers.length;i++){var header=headers[i];if(header.classList.contains('t585__opened'))oldIndex=i;if(header===element)newIndex=i}
return oldIndex<newIndex?!0:!1}
function t585__calcHeight(element,container,activeHeight,isAccordionDown){var windowHeight=window.innerHeight;var windowScroll=window.scrollY;var containerHeight=container.scrollHeight;var accordionHeight=containerHeight+element.offsetHeight;var elementTopOffset=element.getBoundingClientRect().top+windowScroll;var target=isAccordionDown?elementTopOffset-activeHeight:elementTopOffset;if(target<windowScroll||accordionHeight>windowHeight){t585__scroll(target)}}
function t585__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t585__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t585__animateScroll(){currentTime+=increment;window.scrollTo(0,t585__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t585__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t585__animateScroll()}
function t635_init(recid){var el=$("#rec"+recid);var data=el.find(".t635__textholder");var animRecId=data.attr("data-recid");var screenmin=parseInt($("#rec"+animRecId).attr("data-screen-min"),10);var screenmax=parseInt($("#rec"+animRecId).attr("data-screen-max"),10);if(isNaN(screenmax)&&isNaN(screenmin)){t635_startType(recid)}else if(!isNaN(screenmax)&&!isNaN(screenmin)){if($(window).width()>=screenmin&&$(window).width()<=screenmax){t635_startType(recid)}}else if(!isNaN(screenmax)){if($(window).width()<=screenmax){t635_startType(recid)}}else if(!isNaN(screenmin)){if($(window).width()>=screenmin){t635_startType(recid)}}}
function t635_startType(recid){var t635_el=$('#rec'+recid),t635_data=t635_el.find(".t635__textholder"),t635_animRecId=t635_data.attr("data-recid"),t635_animText=t635_findAnimElem(t635_animRecId),t635_phrasesList=[],t635_phrase1=t635_data.attr("data-text1"),t635_phrase2=t635_data.attr("data-text2"),t635_phrase3=t635_data.attr("data-text3"),t635_phrase4=t635_data.attr("data-text4"),t635_phrase5=t635_data.attr("data-text5"),t635_speed=t635_data.attr("data-speed"),t635_loop=t635_data.attr("data-loop"),t635_backspaceDelay=t635_data.attr("data-backspacing-delay");if(typeof t635_animText=="undefined"){return}
if(typeof t635_phrase1!="undefined"){t635_phrasesList.push(t635_phrase1.slice(0,80))}
if(typeof t635_phrase2!="undefined"){t635_phrasesList.push(t635_phrase2.slice(0,80))}
if(typeof t635_phrase3!="undefined"){t635_phrasesList.push(t635_phrase3.slice(0,80))}
if(typeof t635_phrase4!="undefined"){t635_phrasesList.push(t635_phrase4.slice(0,80))}
if(typeof t635_phrase5!="undefined"){t635_phrasesList.push(t635_phrase5.slice(0,80))}
if(t635_animText.length!==0&&t635_phrasesList.length!==0){var t635_animTextHtml=t635_animText.html(),t635_animTextSplitted=t635_animTextHtml.split("|"),t635_curWin=$(window);t635_animText.html(t635_animTextSplitted[0]+"<span class=\"t635__typing-text\"></span>"+t635_animTextSplitted[1]);t635_updateAnimTextLimits(t635_animRecId);t635_curWin.bind('resize',t_throttle(function(){t635_updateAnimTextLimits(t635_animRecId)},200));var intervalUpdate=setInterval(function(){t635_updateAnimTextLimits(t635_animRecId)},5000);var t635_animatedText=$("#rec"+t635_animRecId+" .t635__typing-text"),t635_animTextTop=t635_animatedText.attr("data-top-limit"),t635_animTextBottom=t635_animatedText.attr("data-bottom-limit"),t635_winTop=t635_curWin.scrollTop(),t635_winBottom=t635_winTop+t635_curWin.height();t635_animateText(t635_animRecId,t635_phrasesList,t635_speed,t635_loop,t635_backspaceDelay);if(t635_animTextBottom<t635_winTop||t635_animTextTop>t635_winBottom){$("#rec"+t635_animRecId+" .t635__typing-text").data('typed').pauseTyping();$("#rec"+t635_animRecId+" .t635__typing-text").html("")}
t635_curWin.bind('scroll',t_throttle(function(){t635_animTextTop=t635_animatedText.attr("data-top-limit");t635_animTextBottom=t635_animatedText.attr("data-bottom-limit");t635_winTop=t635_curWin.scrollTop();t635_winBottom=t635_winTop+t635_curWin.height();if(t635_animTextBottom<t635_winTop||t635_animTextTop>t635_winBottom){$("#rec"+t635_animRecId+" .t635__typing-text").data('typed').pauseTyping();$("#rec"+t635_animRecId+" .t635__typing-text").html("")}else{$("#rec"+t635_animRecId+" .t635__typing-text").data('typed').continueTyping()}},200))}}
function t635_findAnimElem(animRecId){var animRec=$("#rec"+animRecId);var animH1=animRec.find("h1:contains(\'|\')").last();var animH2=animRec.find("h2:contains(\'|\')").last();var animH3=animRec.find("h3:contains(\'|\')").last();var animDiv=animRec.find("div:contains(\'|\')").last();if(typeof animH1!="undefined"&&animH1.length>0){return animH1}
if(typeof animH2!="undefined"&&animH2.length>0){return animH2}
if(typeof animH3!="undefined"&&animH3.length>0){return animH3}
if(typeof animDiv!="undefined"&&animDiv.length>0){return animDiv}}
function t635_updateAnimTextLimits(t635_animRecId){var t635_animatedBlock=$("#rec"+t635_animRecId),t635_animatedText=t635_animatedBlock.find(".t635__typing-text");if(typeof t635_animatedText.offset()!='undefined'){t635_animatedText.attr("data-top-limit",t635_animatedText.offset().top);t635_animatedText.attr("data-bottom-limit",(t635_animatedBlock.offset().top+t635_animatedBlock.height()))}}
function t635_animateText(t635_animRecId,t635_phrasesList,t635_speed,t635_loop,t635_backspaceDelay){if(typeof t635_speed=="undefined"){t635_speed=40}
if(typeof t635_backspaceDelay=="undefined"){t635_backspaceDelay=800}
if(typeof t635_loop=="undefined"){t635_loop=!0}else{t635_loop=!1}
$("#rec"+t635_animRecId+" .t635__typing-text").typed({strings:t635_phrasesList,typeSpeed:t635_speed*1,startDelay:600,backSpeed:10,backDelay:t635_backspaceDelay*1,loop:t635_loop,contentType:'text'})}
function t958_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t958');if(!container)return;var sliderContainer=rec.querySelector('.t958__slidecontainer');var items=rec.querySelectorAll('.t958__item');var cards=rec.querySelectorAll('.t958__card');var totalSlides=items.length;if(!totalSlides){return}
var sliderWidth=parseFloat(getComputedStyle(items[0],null).width.replace('px',''));t958_checkSize(rec);sliderContainer.style.width=(sliderWidth*totalSlides)+'px';window.addEventListener('resize',t_throttle(function(){t958_findVisibleCards(rec);t958_initPopup(rec);t958_checkSize(rec);sliderWidth=parseFloat(getComputedStyle(items[0],null).width.replace('px',''));sliderContainer.style.width=(sliderWidth*totalSlides)+'px';var matrix=(getComputedStyle(sliderContainer,null).transform||'').replace(/[^0-9\-.,]/g,'').split(',');var x=matrix[12]||matrix[4];if(-((totalSlides-1)*sliderWidth)>x){sliderContainer.style.transform='translate(-'+(totalSlides-1)*sliderWidth+'px, 0)'}}));if(typeof jQuery!=='undefined'){$(container).bind('displayChanged',function(){sliderContainer.style.width='100%';setTimeout(function(){sliderWidth=parseFloat(getComputedStyle(items[0],null).width.replace('px',''));sliderContainer.style.width=(sliderWidth*totalSlides)+'px';t958_checkSize(rec);t958_findVisibleCards(rec);t958_initPopup(rec)},300)})}else{container.addEventListener('displayChanged',function(){sliderContainer.style.width='100%';setTimeout(function(){sliderWidth=parseFloat(getComputedStyle(items[0],null).width.replace('px',''));sliderContainer.style.width=(sliderWidth*totalSlides)+'px';t958_checkSize(rec);t958_findVisibleCards(rec);t958_initPopup(rec)},300)})}
rec.querySelector('.t958__next').addEventListener('click',function(){t958_slide(rec,'right')});rec.querySelector('.t958__previous').addEventListener('click',function(){t958_slide(rec,'left')});if(window.innerWidth>640){t958_findVisibleCards(rec)}else{t_onFuncLoad('Hammer',function(){t958_initSliderSwipe(rec)});for(var i=0;i<cards.length;i++){cards[i].classList.add('t958__card-visible')}}
t958_initPopup(rec)}
function t958_checkSize(rec){var cards=rec.querySelectorAll('.t958__card_preview');var mores=rec.querySelectorAll('.t958__more-wrapper');var blockHeight=rec.querySelector('.t958__height');var maxWidth=parseFloat(getComputedStyle(blockHeight,null).width.replace('px',''));var windowMargin=80;var windowWidth=window.innerWidth;var cardMaxWidth=windowWidth-windowMargin;if(maxWidth>windowWidth){for(var i=0;i<cards.length;i++){cards[i].style.maxWidth=cardMaxWidth+'px'}
for(var i=0;i<mores.length;i++){mores[i].style.maxWidth=cardMaxWidth+'px'}}else{for(var i=0;i<cards.length;i++){cards[i].style.maxWidth=''}
for(var i=0;i<mores.length;i++){mores[i].style.maxWidth=''}}
for(var i=0;i<cards.length;i++){var card=cards[i];var cardStyle=getComputedStyle(card,null);var cardPaddingTop=parseInt(cardStyle.paddingTop)||0;var cardPaddingBottom=parseInt(cardStyle.paddingBottom)||0;var cardHeight=card.clientHeight-(cardPaddingTop+cardPaddingBottom);var cardInner=card.querySelector('.t958__card-inner');var cardInnerHeight=cardInner.offsetHeight;if(cardHeight<=cardInnerHeight){card.classList.add('t958__card_fade')}else{card.classList.remove('t958__card_fade')}}}
function t958_initSliderSwipe(rec){var sliderWrapper=rec.querySelector('.t958__gallery');var totalSlides=rec.querySelectorAll('.t958__item').length;var timeout;var isScrolling=!1;if(typeof Hammer!=='undefined'){delete Hammer.defaults.cssProps.userSelect;var hammer=new Hammer(sliderWrapper,{domEvents:!0,inputClass:Hammer.TouchInput,recognizers:[[Hammer.Swipe,{direction:Hammer.DIRECTION_HORIZONTAL}]]});window.addEventListener('scroll',function(){isScrolling=!0;clearTimeout(timeout);timeout=setTimeout(function(){isScrolling=!1},250)});if(totalSlides==1)return!1;hammer.on('swipeleft',function(event){if(isScrolling)return!1;sliderWrapper.setAttribute('data-slider-touch','yes');if(event.isFinal){t958_slide(rec,'right');sliderWrapper.setAttribute('data-slider-touch','')}});hammer.on('swiperight',function(event){if(isScrolling)return!1;sliderWrapper.setAttribute('data-slider-touch','yes');if(event.isFinal){t958_slide(rec,'left');sliderWrapper.setAttribute('data-slider-touch','')}})}}
function t958_slide(rec,direction){var allrecords=document.getElementById('allrecords');var container=rec.querySelector('.t958__slidecontainer');var items=rec.querySelectorAll('.t958__item');var totalSlides=items.length;var sliderWidth=parseFloat(getComputedStyle(items[0],null).width.replace('px',''));var position=parseInt(container.getAttribute('data-slide-pos'),10);if(direction==='right'){container.setAttribute('data-slide-pos',++position);if(position>=totalSlides){position=0;container.setAttribute('data-slide-pos',position)}}else{container.setAttribute('data-slide-pos',--position);if(position<=-1){position=totalSlides-1;container.setAttribute('data-slide-pos',position)}}
container.style.transform='translate(-'+sliderWidth*position+'px, 0)';container.style.transitionDuration='.3s';setTimeout(function(){t958_findVisibleCards(rec)},350);if(window.lazy==='y'||allrecords.getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t958_findVisibleCards(rec){var cards=rec.querySelectorAll('.t958__card');var prevControl=rec.querySelector('.t958__previous');var nextControl=rec.querySelector('.t958__next');for(var i=0;i<cards.length;i++){var card=cards[i];card.classList.remove('t958__card-left');card.classList.remove('t958__card-right');card.classList.remove('t958__card-visible');var windowWidth=window.innerWidth;var cardLeftPos=card.getBoundingClientRect().left;var cardRightPos=cardLeftPos+parseFloat(getComputedStyle(card,null).width.replace('px',''));if(cardLeftPos<=0&&cardRightPos>=0){card.classList.add('t958__card-left')}else if(cardLeftPos<=windowWidth&&cardRightPos>=windowWidth){card.classList.add('t958__card-right')}else if(cardLeftPos>=0&&cardRightPos<=windowWidth){card.classList.add('t958__card-visible')}}
var leftCard=rec.querySelector('.t958__card-left');var rightCard=rec.querySelector('.t958__card-right');if(leftCard){var leftCardRect=leftCard.getBoundingClientRect().left;var leftCardWidth=parseFloat(getComputedStyle(leftCard,null).width.replace('px',''));var leftCardOffset=leftCardWidth-Math.abs(leftCardRect);if(leftCardOffset>=30){prevControl.style.width=leftCardOffset+'px'}else{prevControl.style.width=100+'px'}}
if(rightCard){var rightCardRect=rightCard.getBoundingClientRect().left;var rightCardStyle=getComputedStyle(rightCard,null);var paddingLeft=parseInt(rightCardStyle.paddingLeft)||0;var paddingRight=parseInt(rightCardStyle.paddingRight)||0;var rightCardWidth=rightCard.clientWidth-(paddingLeft+paddingRight);var rightCardOffset=rightCardWidth-(rightCardRect+rightCardWidth-window.innerWidth);if(rightCardOffset>=30){nextControl.style.width=rightCardOffset+'px'}else{nextControl.style.width=100+'px'}}}
function t958_initPopup(rec){if(rec.querySelector('.t958').classList.contains('t958_preview'))return;var fadeCards=rec.querySelectorAll('.t958__card_fade[data-review-block^="review"]');for(var i=0;i<fadeCards.length;i++){fadeCards[i].addEventListener('click',function(){var card=this;if(card.classList.contains('t958__card-visible')){t958_showPopup(rec);var popup=rec.querySelector('.t-popup');var reviewId=card.getAttribute('data-review-block').replace('review','');var reviewPopup=popup.querySelector('.t958__popup-item[data-review-index="'+reviewId+'"]');var popupItems=popup.querySelectorAll('.t958__popup-item');for(var i=0;i<popupItems.length;i++){popupItems[i].style.display='none'}
reviewPopup.style.display='block'}})}}
function t958_checkPopupSize(rec){var popupContainer=rec.querySelector('.t-popup__container');var popupHeight=parseFloat(getComputedStyle(popupContainer,null).height.replace('px',''));var windowMargin=120;var windowHeight=window.innerHeight-windowMargin;if(popupHeight>windowHeight){popupContainer.classList.add('t-popup__container-static')}else{popupContainer.classList.remove('t-popup__container-static')}}
function t958_showPopup(rec){var allrecords=document.getElementById('allrecords');var popup=rec.querySelector('.t-popup');var popupContainer=rec.querySelector('.t-popup__container');var popupClose=rec.querySelector('.t-popup__close');popup.style.display='block';setTimeout(function(){popupContainer.classList.add('t-popup__container-animated');popup.classList.add('t-popup_show');t958_checkPopupSize(rec);if(window.lazy==='y'||allrecords.getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},50);document.body.classList.add('t-body_popupshowed');popup.removeEventListener('mousedown',t958_mousedownEvent);popup.addEventListener('mousedown',t958_mousedownEvent);popupClose.removeEventListener('click',t958_closePopup);popupClose.addEventListener('click',t958_closePopup);document.removeEventListener('keydown',t958_keydownEvent);document.addEventListener('keydown',t958_keydownEvent)}
function t958_mousedownEvent(event){var windowWidth=window.innerWidth;var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(event.clientX>windowWithoutScrollBar)return;if(event.target==this)t958_closePopup()}
function t958_keydownEvent(event){if(event.keyCode==27)t958_closePopup()}
function t958_closePopup(){var popupShow=document.querySelector('.t-popup.t-popup_show');if(popupShow){document.body.classList.remove('t-body_popupshowed');popupShow.classList.remove('t-popup_show');setTimeout(function(){var popups=document.querySelectorAll('.t-popup:not(.t-popup_show)');document.body.scrollTop=0;for(var i=0;i<popups.length;i++){popups[i].style.display='none'}},300)}}